export enum SolarActionTypes {
  SET_SOLAR_DATA = 'SET_SOLAR_DATA',
  GET_SOLAR_DATA = 'GET_SOLAR_DATA',
  GET_CHART_MEASUREMENTS = 'GET_CHART_MEASUREMENTS',
	SET_CURRENT_SOLAR_MEASURE = 'SET_CURRENT_SOLAR_MEASURE'
}